#!/bin/sh

# Startup programs
xset -b &
setxkbmap fr &
numlockx on &
pactl set-sink-volume 0 '41%' &
compton --config $HOME/.config/i3/compton.conf &
nm-applet &
solaar &

sh $HOME/.config/i3/arandr.sh &

feh --bg-fill $HOME/.config/i3/wallpaper/arch.png $HOME/.config/i3/wallpaper/arch.png &

megasync &
mpd /etc/mpd.conf &
tilda &
clipmenud &

# Touchpad
synclient TapButton1=1
synclient ClickFinger2=3 TapButton2=3
synclient ClickFinger3=2 TapButton3=2
synclient VertTwoFingerScroll=1
synclient PalmDetect=1
